### ISSUE TITLE
Failled to build

### ISSUE THREAD

**Issue by nshiell** [ericoporto/pyqthelloworld#4]
Running:
`snapcraft && sudo snap install --devmode --dangerous *.snap && pyqthelloworld`

Shows:
`This snapcraft project does not specify the base keyword, explicitly setting the base keyword enables the latest snapcraft features.
This project is best built on 'Ubuntu 16.04', but is building on a 'KDE neon 18.04' host.
Read more about bases at https://docs.snapcraft.io/t/base-snaps/11198
Sorry, an error occurred in Snapcraft:
Issues while validating snapcraft.yaml: The 'parts/pyqthelloworld/prepare' property does not match the required schema: ['execstack --clear-execstack lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5'] is not of type 'string'`

**Comment by ericoporto** [comment]
I don't have KDE neon to verify now but it should build.

The first time it runs will take ages, but consecutive runs will be faster. Building will also take a long time. 

Additionally, now I have a new message on my command line, that I don't know yet what it means.
`Qt: Session management error: None of the authentication protocols specified are supported`

Other than this, it should build and run, on the command line, type `pyqthelloworld`, by clicking the button, it should print to the open prompt.

**Comment by ericoporto** [comment]
Sorry, by should build, I mean, I booted Ubuntu 18.04 and updated the `snapcraft.yaml` file on a new commit https://github.com/ericoporto/pyqthelloworld/commit/c1184d3e694a83f7c2dc538b6b246f885e8b27d8

Please, @nshiell , verify this works for you.

**Comment by nshiell** [comment]
@ericoporto sorry for the late reply
I just checked out 1184d3 and It does now build correctly
